source: 
  path: "hdfs:///Projects/DSJedAI/Resources/data/roads.tsv"
  realIdField: "0"
  geometryField: "1"

target:
  path: "hdfs:///Projects/DSJedAI/Resources/data/buildings.tsv"
  realIdField: "0"
  geometryField: "1"

relation: "DE9IM"

configurations:
  thetaGranularity: "avg"
  gridType: "QUADTREE"
  partitions: "1600"
