source:
  path: "/home/gmandi/Documents/Extreme-Earth/Entity-Resolution/Datasets/s1_images_subset.csv"
  realIdField: "id"
  geometryField: "WKT"

target:
  path: "/home/gmandi/Documents/Extreme-Earth/Entity-Resolution/Datasets/waterways_gr.csv"
  realIdField: "osm_id"
  geometryField: "WKT"

relation: "covers"
theta_measure: "avg"