source:
  path: "/home/gmandi/Documents/Extreme_Earth/Datasets/GEODATA/regions_gr.csv"
  realIdField: "PER"
  geometryField: "WKT"

target:
  path: "/home/gmandi/Documents/Extreme-Earth/Entity-Resolution/Datasets/waterways_gr.csv"
  realIdField: "osm_id"
  geometryField: "WKT"

relation: "covers"
theta_measure: "none"
