source:
  path: "../../Datasets/GEODATA/wildlife_sanctuaries.csv"
  realIdField: "ID"
  geometryField: "WKT"

target:
  path: "../../Datasets/GEOFABRIK/waterways_gr.csv"
  realIdField: "osm_id"
  geometryField: "WKT"
