
source:
  path: "/home/gmandi/Documents/Extreme-Earth/Datasets/SPATIAL-HADOOP/LINEARWATER_100K.tsv"
  realIdField: "1"
  geometryField: "0"

target:
  path: "/home/gmandi/Documents/Extreme-Earth/Datasets/SPATIAL-HADOOP/AREAWATER_100K.tsv"
  realIdField: "1"
  geometryField: "0"

relation: "DE9IM"

configurations:
  thetaGranularity: "avg"
  secondaryWF: "MBRO"
  mainWF: "JS"
  budget: "10000"
  ws: "Hybrid"