source:
  path: "/home/gmandi/Documents/Extreme-Earth/Datasets/polar-uc/IceMonitoring/s1_images_20K.csv"
  realIdField: "id"
  geometryField: "WKT"

target:
  path: "/home/gmandi/Documents/Extreme-Earth/Datasets/polar-uc/IceMonitoring/s1_images_2K.csv"
  realIdField: "id"
  geometryField: "WKT"

relation: "intersects"

configurations:
  blockingAlg: "RADON"
  spatialPartition: "false"
  theta_measure: "avg2"
  matchingAlg: "SPATIAL"
  weighting_strategy: "CBS"
  budget: "1000000"
  gridType: "KDBTREE"
  partitionBy: "source"