
# "/home/gmandi/Documents/Extreme-Earth/Datasets/polar-uc/IceMonitoring/workplace/observations_WKT.csv"
# "/home/gmandi/Documents/Extreme-Earth/Datasets/polar-uc/IceMonitoring/workplace/s1_images_10K.csv"
# "/home/gmandi/Documents/Extreme-Earth/Datasets/polar-uc/IceMonitoring/workplace/observations_WKT/observations_WKT.shp"

source:
  path: "/home/gmandi/Documents/Extreme-Earth/Datasets/polar-uc/IceMonitoring/workplace/s1_images.csv"
  realIdField: "id"
  geometryField: "WKT"
#  dateField: "datetime"
#  datePattern: "yyyy-MM-dd'T'HH:mm:ss"

target:
  path: "/home/gmandi/Documents/Extreme-Earth/Datasets/polar-uc/IceMonitoring/workplace/observations_WKT.csv"
  geometryField: "WKT"
  realIdField: "id"
#  dateField: "observed_a"
#  datePattern: "yyyy-MM-dd HH:mm:ss"

relation: "DE9IM"

configurations:
  partitions: "12"
  thetaGranularity: "avg"
  matchingAlg: "GIANT"
  gridType: "QUADTREE"
  weightingStrategy: "JS"