source:
  path: "/home/gmandi/Documents/Extreme-Earth/Datasets/polar-uc/IceMonitoring/s1_images_20K.csv"
  realIdField: "id"
  geometryField: "WKT"

target:
  path: "/home/gmandi/Documents/Extreme-Earth/Datasets/polar-uc/IceMonitoring/s1_images_20K.csv"
  realIdField: "id"
  geometryField: "WKT"

relation: "intersects"

configurations:
  partitions: "40"
  theta_measure: "avg2"
  matchingAlg: "PROGRESSIVE_LIGHT_RADON"
  gridType: "QUADTREE"
  weighting_strategy: "JS"