source:
  path: "/home/gmandi/Documents/Extreme-Earth/Entity-Resolution/Datasets/polar-uc-cm/s1_images_10K.csv"
  realIdField: "id"
  geometryField: "WKT"

target:
  path: "/home/gmandi/Documents/Extreme-Earth/Entity-Resolution/Datasets/polar-uc-cm/observations_WKT.csv"
  realIdField: "id"
  geometryField: "WKT"

relation: "contains"

configurations:
  blockingAlg: "RADON"
  spatialPartition: "false"
  theta_measure: "avg"
  matchingAlg: "SPATIAL"
  weighting_strategy: "JS"