source:
  path: "/home/gmandi/Documents/Extreme-Earth/Datasets/polar-uc/IceMonitoring/workplace/s1_images_10K.csv"
  realIdField: "id"
  geometryField: "WKT"
  dateField: "datetime"
  datePattern: "yyyy-MM-dd'T'HH:mm:ss"

target:
  path: "/home/gmandi/Documents/Extreme-Earth/Datasets/polar-uc/IceMonitoring/workplace/observations_WKT.csv"
  geometryField: "WKT"
  realIdField: "id"
  dateField: "observed_at"
  datePattern: "YYYY-MM-DD HH:MM:SS"

relation: "DE9IM"

configurations:
  partitions: "12"
  theta_measure: "avg"
  matchingAlg: "GIANT"
  gridType: "QUADTREE"
  weighting_strategy: "JS"