source:
  path: "/home/gmandi/Documents/Extreme_Earth/Entity_Resolution/Polar-UseCase/Data/CSV/WKT/s1_images_10K.csv"
  realIdField: "id"
  geometryField: "WKT"

target:
  path: "/home/gmandi/Documents/Extreme_Earth/Entity_Resolution/Polar-UseCase/Data/CSV/WKT/observations_WKT.csv"
  realIdField: "id"
  geometryField: "WKT"

relation: "contains"

configurations:
  blockingAlg: "RADON"
  partitions: "12"
  spatialPartition: "false"
  theta_measure: "none"
  prioritization_alg: "COMPARISON_CENTRIC"
  weighting_strategy: "ECBS"